spring:
  datasource:
    url: jdbc:h2:mem:ably;MODE=MySQL;DB_CLOSE_DELAY=-1
    hikari:
      minimum-idle: 20
      maximum-pool-size: 20
      max-lifetime: 1000000
      data-source-properties:
        cachePrepsStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
      username: sa
      password: sa
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
